import 'package:flutter/material.dart';
import 'package:trent_u_class_find/models/center/center.dart';
import 'package:trent_u_class_find/models/enums/enums.dart';
import 'package:trent_u_class_find/models/floor/floor.dart';
import 'package:trent_u_class_find/models/room/room.dart';

import 'package:trent_u_class_find/services/theme_mode_notifier_service/theme_mode_notifier_service.dart';

ThemeMode? appThemeMode = ThemeMode.system;

TargetPlatform? appTargetPlatform = TargetPlatform.android;

int? appThemeSettingsInt = 2;
int? appImageQualityViewSettingsInt = 1;
int? appImageQualityDownloadSettingsInt = 1;

ThemeModeNotifierService? globalThemeModeNotifier;

FocusNode? quickSearchFocusNode;

GlobalKey<FormState>? quickSearchFormKey;

late AnimationController? campusLinksMenuAnimationController;
ScrollController? buildingsPageScrollController;
TextEditingController? quickSearchController;

ExpansionTileController? campusLinksMenuController;

late Animation<double>? campusLinksMenuAnimationProgress;

List<TrentCenterModel?> trentCentersDB = <TrentCenterModel?>[
  TrentCenterModel(
    trentCenterName: 'Bata Library',
    trentCenterCode: 'BL',
    trentCenter: TrentCenters.bataLibrary,
    reviewImageAssetPath: 'assets/images/review/BL_Center.jpg',
    hDImageAssetPath: 'assets/images/720/BL_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: '1st Floor',
        floorCenter: TrentCenters.bataLibrary,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '102',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Language Lab',
            roomCapacity: '26',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata102.jpg',
            hDImageAssetPath: 'assets/images/720/bata102.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata102.jpg',
          ),
          TrentRoomModel(
            roomNumber: '103',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Film Theater',
            roomCapacity: '64',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata103.jpg',
            hDImageAssetPath: 'assets/images/720/bata103.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata103.jpg',
          ),
          TrentRoomModel(
            roomNumber: '107.1',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata107.1.jpg',
            hDImageAssetPath: 'assets/images/720/bata107.1.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata107.1.jpg',
          ),
          TrentRoomModel(
            roomNumber: '107.2',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata107.2.jpg',
            hDImageAssetPath: 'assets/images/720/bata107.2.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata107.2.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '2',
        floorName: '2nd Floor',
        floorCenter: TrentCenters.bataLibrary,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '201',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Computer Lab',
            roomCapacity: '9',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata201.jpg',
            hDImageAssetPath: 'assets/images/720/bata201.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata201.jpg',
          ),
          TrentRoomModel(
            roomNumber: '210',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Computer Lab',
            roomCapacity: '20',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata210.jpg',
            hDImageAssetPath: 'assets/images/720/bata210.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata210.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '3',
        floorName: '3rd Floor',
        floorCenter: TrentCenters.bataLibrary,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '314',
            roomFloor: '3rd Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata314.jpg',
            hDImageAssetPath: 'assets/images/720/bata314.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata314.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '4',
        floorName: '4th Floor',
        floorCenter: TrentCenters.bataLibrary,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '401',
            roomFloor: '4th Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Seminar Room',
            roomCapacity: '30',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata401.jpg',
            hDImageAssetPath: 'assets/images/720/bata401.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata401.jpg',
          ),
          TrentRoomModel(
            roomNumber: '402',
            roomFloor: '4th Floor',
            roomCenter: TrentCenters.bataLibrary,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'BL',
            reviewImageAssetPath: 'assets/images/review/bata402.jpg',
            hDImageAssetPath: 'assets/images/720/bata402.jpg',
            fHDImageAssetPath: 'assets/images/1080/bata402.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Champlain College',
    trentCenterCode: 'CCN',
    otherTrentCenterCodes: <String?>[
      'CCS',
      'CCW',
    ],
    trentCenter: TrentCenters.champlainCollege,
    reviewImageAssetPath: 'assets/images/review/CC_Center.jpg',
    hDImageAssetPath: 'assets/images/720/CC_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: 'All Floors',
        floorCenter: TrentCenters.champlainCollege,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'Bike',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Outdoor',
            roomCapacity: 'N/A',
            centerCode: 'N/A',
            reviewImageAssetPath: 'assets/images/review/bike5.jpg',
            hDImageAssetPath: 'assets/images/720/bike5.jpg',
            fHDImageAssetPath: 'assets/images/1080/bike5.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'G4',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'CCN',
            reviewImageAssetPath: 'assets/images/review/CCNG4.jpg',
            hDImageAssetPath: 'assets/images/720/CCNG4.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCNG4.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'I1',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'CCN',
            reviewImageAssetPath: 'assets/images/review/CCNI1.jpg',
            hDImageAssetPath: 'assets/images/720/CCNI1.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCNI1.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'I2',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Seminar Room',
            roomCapacity: '14',
            centerCode: 'CCN',
            reviewImageAssetPath: 'assets/images/review/CCNI2.jpg',
            hDImageAssetPath: 'assets/images/720/CCNI2.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCNI2.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'K1',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'CCN',
            reviewImageAssetPath: 'assets/images/review/CCNK1.jpg',
            hDImageAssetPath: 'assets/images/720/CCNK1.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCNK1.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'M2',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Council Chamber',
            roomCapacity: '60',
            centerCode: 'CCN',
            reviewImageAssetPath: 'assets/images/review/CCNM2.jpg',
            hDImageAssetPath: 'assets/images/720/CCNM2.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCNM2.jpg',
          ),
          TrentRoomModel(
            roomNumber: '307',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Lecture Hall',
            roomCapacity: '140',
            centerCode: 'CCS',
            reviewImageAssetPath: 'assets/images/review/CCS307.jpg',
            hDImageAssetPath: 'assets/images/720/CCS307.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCS307.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'A1',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'CCW',
            reviewImageAssetPath: 'assets/images/review/CCWA1.jpg',
            hDImageAssetPath: 'assets/images/720/CCWA1.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCWA1.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'A2',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Seminar Room',
            roomCapacity: '35',
            centerCode: 'CCW',
            reviewImageAssetPath: 'assets/images/review/CCWA2.jpg',
            hDImageAssetPath: 'assets/images/720/CCWA2.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCWA2.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'C3',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'CCW',
            reviewImageAssetPath: 'assets/images/review/CCWC3.jpg',
            hDImageAssetPath: 'assets/images/720/CCWC3.jpg',
            fHDImageAssetPath: 'assets/images/1080/CCWC3.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'The Seasoned Spoon Café',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.champlainCollege,
            roomType: 'Café',
            roomCapacity: 'N/A',
            centerCode: 'N/A',
            reviewImageAssetPath: 'assets/images/review/seasonedspoon4.jpg',
            hDImageAssetPath: 'assets/images/720/seasonedspoon4.jpg',
            fHDImageAssetPath: 'assets/images/1080/seasonedspoon4.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Chemical Sciences Building',
    trentCenterCode: 'CSB',
    trentCenter: TrentCenters.chemicalScience,
    reviewImageAssetPath: 'assets/images/review/CSB_Center.jpg',
    hDImageAssetPath: 'assets/images/720/CSB_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: '1st Floor',
        floorCenter: TrentCenters.chemicalScience,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'D101',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.chemicalScience,
            roomType: 'Chemistry Lab',
            roomCapacity: 'N/A',
            centerCode: 'CSB',
            reviewImageAssetPath: 'assets/images/review/CSBD101.jpg',
            hDImageAssetPath: 'assets/images/720/CSBD101.jpg',
            fHDImageAssetPath: 'assets/images/1080/CSBD101.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D109',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.chemicalScience,
            roomType: 'Chemistry Lab',
            roomCapacity: 'N/A',
            centerCode: 'CSB',
            reviewImageAssetPath: 'assets/images/review/CSBD109.jpg',
            hDImageAssetPath: 'assets/images/720/CSBD109.jpg',
            fHDImageAssetPath: 'assets/images/1080/CSBD109.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D113',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.chemicalScience,
            roomType: 'Chemistry Lab',
            roomCapacity: 'N/A',
            centerCode: 'CSB',
            reviewImageAssetPath: 'assets/images/review/CSBD113.jpg',
            hDImageAssetPath: 'assets/images/720/CSBD113.jpg',
            fHDImageAssetPath: 'assets/images/1080/CSBD113.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D116',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.chemicalScience,
            roomType: 'Chemistry Lab',
            roomCapacity: 'N/A',
            centerCode: 'CSB',
            reviewImageAssetPath: 'assets/images/review/CSBD116.jpg',
            hDImageAssetPath: 'assets/images/720/CSBD116.jpg',
            fHDImageAssetPath: 'assets/images/1080/CSBD116.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'E101',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.chemicalScience,
            roomType: 'Chemistry Lab',
            roomCapacity: '25',
            centerCode: 'CSB',
            reviewImageAssetPath: 'assets/images/review/CSBE101.jpg',
            hDImageAssetPath: 'assets/images/720/CSBE101.jpg',
            fHDImageAssetPath: 'assets/images/1080/CSBE101.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'E103',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.chemicalScience,
            roomType: 'Chemistry Lab',
            roomCapacity: 'N/A',
            centerCode: 'CSB',
            reviewImageAssetPath: 'assets/images/review/CSBE103.jpg',
            hDImageAssetPath: 'assets/images/720/CSBE103.jpg',
            fHDImageAssetPath: 'assets/images/1080/CSBE103.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'DNA Building',
    trentCenterCode: 'DNA',
    trentCenter: TrentCenters.dNABuilding,
    reviewImageAssetPath: 'assets/images/review/DNA_Center.jpg',
    hDImageAssetPath: 'assets/images/720/DNA_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: '1st Floor',
        floorCenter: TrentCenters.dNABuilding,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'D103',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Biology Lab',
            roomCapacity: 'N/A',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAD103.jpg',
            hDImageAssetPath: 'assets/images/720/DNAD103.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAD103.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B104',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Lecture Hall',
            roomCapacity: '60',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAB104.jpg',
            hDImageAssetPath: 'assets/images/720/DNAB104.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAB104.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B105',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Seminar Room',
            roomCapacity: '30',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAB105.jpg',
            hDImageAssetPath: 'assets/images/720/DNAB105.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAB105.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D105',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Biology Lab',
            roomCapacity: 'N/A',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAD105.jpg',
            hDImageAssetPath: 'assets/images/720/DNAD105.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAD105.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D106',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Biology Lab',
            roomCapacity: 'N/A',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAD106.jpg',
            hDImageAssetPath: 'assets/images/720/DNAD106.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAD106.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B108',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Biology Lab',
            roomCapacity: 'N/A',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAB108.jpg',
            hDImageAssetPath: 'assets/images/720/DNAB108.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAB108.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B110.1',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Classroom',
            roomCapacity: '40',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAB110.1.jpg',
            hDImageAssetPath: 'assets/images/720/DNAB110.1.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAB110.1.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D110.2',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Classroom',
            roomCapacity: '40',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAD110.2.jpg',
            hDImageAssetPath: 'assets/images/720/DNAD110.2.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAD110.2.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B113',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Forensics Lab',
            roomCapacity: '25',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAB113.jpg',
            hDImageAssetPath: 'assets/images/720/DNAB113.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAB113.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'C141',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Nursing Lab',
            roomCapacity: '25',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAC141.jpg',
            hDImageAssetPath: 'assets/images/720/DNAC141.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAC141.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'C142',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Nursing Lab',
            roomCapacity: '25',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAC142.jpg',
            hDImageAssetPath: 'assets/images/720/DNAC142.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAC142.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '2',
        floorName: '2nd Floor',
        floorCenter: TrentCenters.dNABuilding,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'D202',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Biology Lab',
            roomCapacity: 'N/A',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAD202.jpg',
            hDImageAssetPath: 'assets/images/720/DNAD202.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAD202.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D208',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Biology Lab',
            roomCapacity: 'N/a',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAD208.jpg',
            hDImageAssetPath: 'assets/images/720/DNAD208.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAD208.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'C215',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Anthro Morin Lab',
            roomCapacity: 'N/A',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAC215.jpg',
            hDImageAssetPath: 'assets/images/720/DNAC215.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAC215.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'C231',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Anthro/Forensics Lab',
            roomCapacity: '30',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAC231.jpg',
            hDImageAssetPath: 'assets/images/720/DNAC231.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAC231.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'C233',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.dNABuilding,
            roomType: 'Anthro Lab',
            roomCapacity: '25',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAC233.jpg',
            hDImageAssetPath: 'assets/images/720/DNAC233.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAC233.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Lady Eaton College',
    trentCenterCode: 'ECC',
    trentCenter: TrentCenters.ladyEatonCollege,
    reviewImageAssetPath: 'assets/images/review/ECC_Center.jpg',
    hDImageAssetPath: 'assets/images/720/ECC_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '2',
        floorName: '2nd Floor',
        floorCenter: TrentCenters.ladyEatonCollege,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '201',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.ladyEatonCollege,
            roomType: 'Lecture Hall',
            roomCapacity: '100',
            centerCode: 'ECC',
            reviewImageAssetPath: 'assets/images/review/ECC201.jpg',
            hDImageAssetPath: 'assets/images/720/ECC201.jpg',
            fHDImageAssetPath: 'assets/images/1080/ECC201.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'D208',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.ladyEatonCollege,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'DNA',
            reviewImageAssetPath: 'assets/images/review/DNAD208.jpg',
            hDImageAssetPath: 'assets/images/720/DNAD208.jpg',
            fHDImageAssetPath: 'assets/images/1080/DNAD208.jpg',
          ),
          TrentRoomModel(
            roomNumber: '208',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.ladyEatonCollege,
            roomType: 'Seminar Room',
            roomCapacity: '40',
            centerCode: 'ECC',
            reviewImageAssetPath: 'assets/images/review/ECC208.jpg',
            hDImageAssetPath: 'assets/images/720/ECC208.jpg',
            fHDImageAssetPath: 'assets/images/1080/ECC208.jpg',
          ),
          TrentRoomModel(
            roomNumber: '212',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.ladyEatonCollege,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'ECC',
            reviewImageAssetPath: 'assets/images/review/ECC212.jpg',
            hDImageAssetPath: 'assets/images/720/ECC212.jpg',
            fHDImageAssetPath: 'assets/images/1080/ECC212.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Environmental Science Center',
    trentCenterCode: 'ESC',
    trentCenter: TrentCenters.enviroScienceCenter,
    reviewImageAssetPath: 'assets/images/review/ESC_Center.jpg',
    hDImageAssetPath: 'assets/images/720/ESC_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: '1st Floor',
        floorCenter: TrentCenters.enviroScienceCenter,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'C111.3',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Geomorphology Lab',
            roomCapacity: 'N/A',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCC111.3.jpg',
            hDImageAssetPath: 'assets/images/720/ESCC111.3.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCC111.3.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '2',
        floorName: '2nd Floor',
        floorCenter: TrentCenters.enviroScienceCenter,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'A202',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'ERS Lab',
            roomCapacity: 'N/A',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCA202.jpg',
            hDImageAssetPath: 'assets/images/720/ESCA202.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCA202.jpg',
          ),
          TrentRoomModel(
            roomNumber: '208',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Seminar Room',
            roomCapacity: '40',
            centerCode: 'ECC',
            reviewImageAssetPath: 'assets/images/review/ECC208.jpg',
            hDImageAssetPath: 'assets/images/720/ECC208.jpg',
            fHDImageAssetPath: 'assets/images/1080/ECC208.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'C202',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Geography Lab',
            roomCapacity: 'N/A',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCC202.jpg',
            hDImageAssetPath: 'assets/images/720/ESCC202.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCC202.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B203',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Workshop',
            roomCapacity: '40',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCB203.jpg',
            hDImageAssetPath: 'assets/images/720/ESCB203.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCB203.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'A205',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Education Lab',
            roomCapacity: 'N/A',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCA205.jpg',
            hDImageAssetPath: 'assets/images/720/ESCA205.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCA205.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'A209',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Education Lab',
            roomCapacity: 'N/A',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCA209.jpg',
            hDImageAssetPath: 'assets/images/720/ESCA209.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCA209.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '3',
        floorName: '3rd Floor',
        floorCenter: TrentCenters.enviroScienceCenter,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'B305',
            roomFloor: '3rd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCB305.jpg',
            hDImageAssetPath: 'assets/images/720/ESCB305.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCB305.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B305.1',
            roomFloor: '3rd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Rooftop Gardens',
            roomCapacity: 'N/A',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/enviroscience30.jpg',
            hDImageAssetPath: 'assets/images/720/enviroscience30.jpg',
            fHDImageAssetPath: 'assets/images/1080/enviroscience30.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'B319',
            roomFloor: '3rd Floor',
            roomCenter: TrentCenters.enviroScienceCenter,
            roomType: 'Workshop',
            roomCapacity: '40',
            centerCode: 'ESC',
            reviewImageAssetPath: 'assets/images/review/ESCB319.jpg',
            hDImageAssetPath: 'assets/images/720/ESCB319.jpg',
            fHDImageAssetPath: 'assets/images/1080/ESCB319.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Gzowski College',
    trentCenterCode: 'FPHL',
    otherTrentCenterCodes: <String?>[
      'GCS',
    ],
    trentCenter: TrentCenters.gzowskiCollege,
    reviewImageAssetPath: 'assets/images/review/GCS_Center.jpg',
    hDImageAssetPath: 'assets/images/720/GCS_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: '1st Floor',
        floorCenter: TrentCenters.gzowskiCollege,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '101',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Performance Space',
            roomCapacity: '80',
            centerCode: 'FPHL',
            reviewImageAssetPath: 'assets/images/review/FPHL101.jpg',
            hDImageAssetPath: 'assets/images/720/FPHL101.jpg',
            fHDImageAssetPath: 'assets/images/1080/FPHL101.jpg',
          ),
          TrentRoomModel(
            roomNumber: '103',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Classroom',
            roomCapacity: '50',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS103-2.jpg',
            hDImageAssetPath: 'assets/images/720/GCS103-2.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS103-2.jpg',
          ),
          TrentRoomModel(
            roomNumber: '105',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Classroom',
            roomCapacity: '40',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS105-3.jpg',
            hDImageAssetPath: 'assets/images/720/GCS105-3.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS105-3.jpg',
          ),
          TrentRoomModel(
            roomNumber: '106',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Classroom',
            roomCapacity: '50',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS106-3.jpg',
            hDImageAssetPath: 'assets/images/720/GCS106-3.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS106-3.jpg',
          ),
          TrentRoomModel(
            roomNumber: '108',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Classroom',
            roomCapacity: '50',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS108-3.jpg',
            hDImageAssetPath: 'assets/images/720/GCS108-3.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS108-3.jpg',
          ),
          TrentRoomModel(
            roomNumber: '110',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Classroom',
            roomCapacity: '30',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS110-2.jpg',
            hDImageAssetPath: 'assets/images/720/GCS110-2.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS110-2.jpg',
          ),
          TrentRoomModel(
            roomNumber: '111',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Classroom',
            roomCapacity: '30',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS111-2.jpg',
            hDImageAssetPath: 'assets/images/720/GCS111-2.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS111-2.jpg',
          ),
          TrentRoomModel(
            roomNumber: '112',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Classroom',
            roomCapacity: '40',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS112-2.jpg',
            hDImageAssetPath: 'assets/images/720/GCS112-2.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS112-2.jpg',
          ),
          TrentRoomModel(
            roomNumber: '114',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Lecture Hall',
            roomCapacity: '230',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS114.jpg',
            hDImageAssetPath: 'assets/images/720/GCS114.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS114.jpg',
          ),
          TrentRoomModel(
            roomNumber: '115',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Case Study Room',
            roomCapacity: '62',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS115.jpg',
            hDImageAssetPath: 'assets/images/720/GCS115.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS115.jpg',
          ),
          TrentRoomModel(
            roomNumber: '117',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Lecture Hall',
            roomCapacity: '130',
            centerCode: 'FPHL',
            reviewImageAssetPath: 'assets/images/review/FPHL117.jpg',
            hDImageAssetPath: 'assets/images/720/FPHL117.jpg',
            fHDImageAssetPath: 'assets/images/1080/FPHL117.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '3',
        floorName: '3rd Floor',
        floorCenter: TrentCenters.gzowskiCollege,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '345',
            roomFloor: '3rd Floor',
            roomCenter: TrentCenters.gzowskiCollege,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'GCS',
            reviewImageAssetPath: 'assets/images/review/GCS345.jpg',
            hDImageAssetPath: 'assets/images/720/GCS345.jpg',
            fHDImageAssetPath: 'assets/images/1080/GCS345.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Otonabee College',
    trentCenterCode: 'OCA',
    trentCenter: TrentCenters.otonabeeCollege,
    reviewImageAssetPath: 'assets/images/review/OCA_Center.jpg',
    hDImageAssetPath: 'assets/images/720/OCA_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: '1st Floor',
        floorCenter: TrentCenters.otonabeeCollege,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: 'W101.2',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Wenjack Theatre',
            roomCapacity: '380',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCW101.2.jpg',
            hDImageAssetPath: 'assets/images/720/OCW101.2.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCW101.2.jpg',
          ),
          TrentRoomModel(
            roomNumber: '109',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Education Room',
            roomCapacity: '40',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA109.jpg',
            hDImageAssetPath: 'assets/images/720/OCA109.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA109.jpg',
          ),
          TrentRoomModel(
            roomNumber: '128',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Education Room',
            roomCapacity: '30',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA128.jpg',
            hDImageAssetPath: 'assets/images/720/OCA128.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA128.jpg',
          ),
          TrentRoomModel(
            roomNumber: '134',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Education Room',
            roomCapacity: '40',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA134.jpg',
            hDImageAssetPath: 'assets/images/720/OCA134.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA134.jpg',
          ),
          TrentRoomModel(
            roomNumber: '143',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Education Room',
            roomCapacity: '50',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA143.jpg',
            hDImageAssetPath: 'assets/images/720/OCA143.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA143.jpg',
          ),
          TrentRoomModel(
            roomNumber: '171',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Sociology Resource Room',
            roomCapacity: '25',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA171.jpg',
            hDImageAssetPath: 'assets/images/720/OCA171.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA171.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '2',
        floorName: '2nd Floor',
        floorCenter: TrentCenters.otonabeeCollege,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '203',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Lecture Hall',
            roomCapacity: '140',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA203.jpg',
            hDImageAssetPath: 'assets/images/720/OCA203.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA203.jpg',
          ),
          TrentRoomModel(
            roomNumber: '204',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Seminar Room',
            roomCapacity: '30',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA204.jpg',
            hDImageAssetPath: 'assets/images/720/OCA204.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA204.jpg',
          ),
          TrentRoomModel(
            roomNumber: '205',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Workshop',
            roomCapacity: '74',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA205.jpg',
            hDImageAssetPath: 'assets/images/720/OCA205.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA205.jpg',
          ),
          TrentRoomModel(
            roomNumber: '206',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Seminar Room',
            roomCapacity: '30',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA206.jpg',
            hDImageAssetPath: 'assets/images/720/OCA206.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA206.jpg',
          ),
          TrentRoomModel(
            roomNumber: '207',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Seminar Room',
            roomCapacity: '30',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA207.jpg',
            hDImageAssetPath: 'assets/images/720/OCA207.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA207.jpg',
          ),
          TrentRoomModel(
            roomNumber: '208',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Workshop',
            roomCapacity: '74',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA208.jpg',
            hDImageAssetPath: 'assets/images/720/OCA208.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA208.jpg',
          ),
          TrentRoomModel(
            roomNumber: '219',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.otonabeeCollege,
            roomType: 'Computer Classroom',
            roomCapacity: '40',
            centerCode: 'OCA',
            reviewImageAssetPath: 'assets/images/review/OCA219.jpg',
            hDImageAssetPath: 'assets/images/720/OCA219.jpg',
            fHDImageAssetPath: 'assets/images/1080/OCA219.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Science Complex',
    trentCenterCode: 'SC',
    trentCenter: TrentCenters.scienceComplex,
    reviewImageAssetPath: 'assets/images/review/SC_Center.jpg',
    hDImageAssetPath: 'assets/images/720/SC_Center.jpg',
    expansionTileController: ExpansionTileController(),
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: '1st Floor',
        floorCenter: TrentCenters.scienceComplex,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '103',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Classroom',
            roomCapacity: '60',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC103-2.jpg',
            hDImageAssetPath: 'assets/images/720/SC103-2.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC103-2.jpg',
          ),
          TrentRoomModel(
            roomNumber: '115',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Classroom',
            roomCapacity: '60',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC115.jpg',
            hDImageAssetPath: 'assets/images/720/SC115.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC115.jpg',
          ),
          TrentRoomModel(
            roomNumber: '137',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Lecture Hall',
            roomCapacity: '265',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC137-2.jpg',
            hDImageAssetPath: 'assets/images/720/SC137-2.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC137-2.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'W1',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SCW1W2.jpg',
            hDImageAssetPath: 'assets/images/720/SCW1W2.jpg',
            fHDImageAssetPath: 'assets/images/1080/SCW1W2.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'W2',
            roomFloor: '1st Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SCW1W2.jpg',
            hDImageAssetPath: 'assets/images/720/SCW1W2.jpg',
            fHDImageAssetPath: 'assets/images/1080/SCW1W2.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '2',
        floorName: '2nd Floor',
        floorCenter: TrentCenters.scienceComplex,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '203',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Classroom',
            roomCapacity: '60',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC203.jpg',
            hDImageAssetPath: 'assets/images/720/SC203.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC203.jpg',
          ),
          TrentRoomModel(
            roomNumber: '208',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Seminar Room',
            roomCapacity: '30',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC208.jpg',
            hDImageAssetPath: 'assets/images/720/SC208.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC208.jpg',
          ),
          TrentRoomModel(
            roomNumber: '215',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Classroom',
            roomCapacity: '60',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC215.jpg',
            hDImageAssetPath: 'assets/images/720/SC215.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC215.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'W3',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SCW3W4.jpg',
            hDImageAssetPath: 'assets/images/720/SCW3W4.jpg',
            fHDImageAssetPath: 'assets/images/1080/SCW3W4.jpg',
          ),
          TrentRoomModel(
            roomNumber: 'W4',
            roomFloor: '2nd Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SCW3W4.jpg',
            hDImageAssetPath: 'assets/images/720/SCW3W4.jpg',
            fHDImageAssetPath: 'assets/images/1080/SCW3W4.jpg',
          ),
        ],
      ),
      TrentFloorModel(
        floorNumber: '3',
        floorName: '3rd Floor',
        floorCenter: TrentCenters.scienceComplex,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '305',
            roomFloor: '3rd Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Physics Lab',
            roomCapacity: 'N/A',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC305.jpg',
            hDImageAssetPath: 'assets/images/720/SC305.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC305.jpg',
          ),
          TrentRoomModel(
            roomNumber: '317',
            roomFloor: '3rd Floor',
            roomCenter: TrentCenters.scienceComplex,
            roomType: 'Physics Lab',
            roomCapacity: 'N/A',
            centerCode: 'SC',
            reviewImageAssetPath: 'assets/images/review/SC317.jpg',
            hDImageAssetPath: 'assets/images/720/SC317.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC317.jpg',
          ),
        ],
      ),
    ],
  ),
  TrentCenterModel(
    trentCenterName: 'Traill Campus',
    trentCenterCode: 'CH',
    reviewImageAssetPath: 'assets/images/review/Traill_Center.jpg',
    hDImageAssetPath: 'assets/images/720/Traill_Center.jpg',
    expansionTileController: ExpansionTileController(),
    otherTrentCenterCodes: <String?>[
      'SH',
      'TC',
      'WH',
      'BG',
    ],
    trentCenter: TrentCenters.traillCampus,
    trentCenterFloors: <TrentFloorModel?>[
      TrentFloorModel(
        floorNumber: '1',
        floorName: 'All Floors',
        floorCenter: TrentCenters.traillCampus,
        expansionTileController: ExpansionTileController(),
        rooms: const <TrentRoomModel?>[
          TrentRoomModel(
            roomNumber: '102',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.traillCampus,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'CH',
            reviewImageAssetPath: 'assets/images/review/CH102.jpg',
            hDImageAssetPath: 'assets/images/720/CH102.jpg',
            fHDImageAssetPath: 'assets/images/1080/CH102.jpg',
          ),
          TrentRoomModel(
            roomNumber: '102.1',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.traillCampus,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'SH',
            reviewImageAssetPath: 'assets/images/review/SC.jpg',
            hDImageAssetPath: 'assets/images/720/SC.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC.jpg',
          ),
          TrentRoomModel(
            roomNumber: '105',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.traillCampus,
            roomType: 'Multi-Purpose Room',
            roomCapacity: '80',
            centerCode: 'SH',
            reviewImageAssetPath: 'assets/images/review/SC.jpg',
            hDImageAssetPath: 'assets/images/720/SC.jpg',
            fHDImageAssetPath: 'assets/images/1080/SC.jpg',
          ),
          TrentRoomModel(
            roomNumber: '101',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.traillCampus,
            roomType: 'Bagnani Hall',
            roomCapacity: '80',
            centerCode: 'BG',
            reviewImageAssetPath: 'assets/images/review/TC101.jpg',
            hDImageAssetPath: 'assets/images/720/TC101.jpg',
            fHDImageAssetPath: 'assets/images/1080/TC101.jpg',
          ),
          TrentRoomModel(
            roomNumber: '102',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.traillCampus,
            roomType: 'Seminar Room',
            roomCapacity: '25',
            centerCode: 'WH',
            reviewImageAssetPath: 'assets/images/review/WH.jpg',
            hDImageAssetPath: 'assets/images/720/WH.jpg',
            fHDImageAssetPath: 'assets/images/1080/WH.jpg',
          ),
          TrentRoomModel(
            roomNumber: '128',
            roomFloor: 'All Floors',
            roomCenter: TrentCenters.traillCampus,
            roomType: 'Seminar Room',
            roomCapacity: '20',
            centerCode: 'WH',
            reviewImageAssetPath: 'assets/images/review/WH.jpg',
            hDImageAssetPath: 'assets/images/720/WH.jpg',
            fHDImageAssetPath: 'assets/images/1080/WH.jpg',
          ),
        ],
      ),
    ],
  ),
];
